const res = {
  employeeDetail: {
    statusOfemployee: "active",
    user: null,
    contacts: [],
    addresses: [],
    bankdetails: [],
    experiences: [],
    skills: [],
    hobbiesRecords: [],
    personalDetial: {
      title: "mrs",
      firstName: "string",
      middleName: "string",
      lastName: "string",
      maidenName: "string",
      gender: "female",
      dob: "1995-07-31T20:15:00.000Z",
      bloodGroup: "B+",
      marriedStatus: "unmarried",
      pan: "p1234",
      aadhar: "123-123-123-123",
    },
    jobDetail: {
      hiringDate: null,
      joiningDate: null,
      modeOfWork: null,
      probationPeriodMonth: null,
      exitDate: null,
      createdAt: "2023-09-23T05:11:52.000Z",
      updatedAt: "2023-09-23T05:11:52.000Z",
      designationLookupId: null,
      CTC: null,
    },
    employeeId: 11,
  },
  message: "Employee created succesfully.",
};
